# Generated by Django 5.1.6 on 2026-02-13 22:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mealplantemplate_alter_mealplan_id_alter_profile_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/')),
                ('prep_time_minutes', models.IntegerField(help_text='Preparation time in minutes')),
                ('cook_time_minutes', models.IntegerField(blank=True, help_text='Cooking time in minutes', null=True)),
                ('servings', models.IntegerField(default=1)),
                ('calories', models.IntegerField(help_text='Calories per serving')),
                ('protein_g', models.FloatField(help_text='Protein in grams')),
                ('carbs_g', models.FloatField(help_text='Carbs in grams')),
                ('fat_g', models.FloatField(help_text='Fat in grams')),
                ('ingredients', models.TextField(help_text='List of ingredients, one per line')),
                ('instructions', models.TextField(help_text='Step-by-step instructions')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags (e.g., Vegan, Keto, Gluten-Free)', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='mealplan',
            name='structured_plan',
            field=models.JSONField(blank=True, help_text='JSON structure of the weekly plan', null=True),
        ),
        migrations.AddField(
            model_name='mealplantemplate',
            name='structured_plan',
            field=models.JSONField(blank=True, help_text='JSON structure of the template', null=True),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Legacy: Rich text content', null=True),
        ),
        migrations.AlterField(
            model_name='mealplantemplate',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
