# Generated by Django 5.1.6 on 2026-02-13 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recipe_mealplan_structured_plan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyupdate',
            name='arm_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklyupdate',
            name='chest_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklyupdate',
            name='compliance_score',
            field=models.IntegerField(blank=True, help_text='Self-reported compliance 0-100%', null=True),
        ),
        migrations.AddField(
            model_name='weeklyupdate',
            name='energy_level',
            field=models.IntegerField(blank=True, help_text='Energy level from 1-10', null=True),
        ),
        migrations.AddField(
            model_name='weeklyupdate',
            name='hips_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklyupdate',
            name='photo_back',
            field=models.ImageField(blank=True, null=True, upload_to='progress_photos/'),
        ),
        migrations.AddField(
            model_name='weeklyupdate',
            name='photo_front',
            field=models.ImageField(blank=True, null=True, upload_to='progress_photos/'),
        ),
        migrations.AddField(
            model_name='weeklyupdate',
            name='photo_side',
            field=models.ImageField(blank=True, null=True, upload_to='progress_photos/'),
        ),
        migrations.AddField(
            model_name='weeklyupdate',
            name='thigh_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklyupdate',
            name='waist_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FoodLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], max_length=20)),
                ('content', models.TextField(help_text='Description of food consumed')),
                ('image', models.ImageField(blank=True, null=True, upload_to='food_logs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='lab_results/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
