# Generated by Django 5.1.6 on 2026-02-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_foodlog_id_alter_labresult_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodlog',
            options={'verbose_name': 'Food Journal Entry', 'verbose_name_plural': 'Food Journal'},
        ),
        migrations.AddField(
            model_name='profile',
            name='is_nutritionist',
            field=models.BooleanField(default=False),
        ),
    ]
