# Generated by Django 5.1.6 on 2026-02-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_nutritionistnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='file',
            field=models.FileField(blank=True, help_text='PDF or image file of the meal plan', null=True, upload_to='meal_plans/'),
        ),
    ]
